channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake-minimal==5.7.1
  - blast=2.9
  - prodigal=2.6.3
  - chewbbaca=3.2.0
  - pip
  - pip:
    - jsonschema<4
    - warlock==1.3.3
    - pytest
    - pytest-cov
    - pytest-profiling
    - coverage
    - pyyaml
    - argh
    - watchdog
    - bifrostlib
