channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - git                 # needed for pip VCS installs
  - snakemake-minimal==8.10.6
  
  # chewBBACA runtime deps (compatible with 3.4.1)
  - numpy=1.24.*          # aligns with chewBBACA’s pin
  - scipy=1.10.*          # required
  - pandas=2.0.*          # <2.1 per requirement
  - plotly>=5.8           # required
  - SPARQLWrapper         # conda package name is lowercase
  - pyrodigal             # required

  - pip
  - pip:
    - pyfaidx
    - biopython
    - jsonschema>4.18.0a1
    - pyopenssl>=24.3.0
    - pytest
    - pytest-cov
    - pytest-profiling
    - coverage
    - pyyaml
    - argh
    - watchdog
    - bifrostlib
    - -e .
