#-Basic info----------------------------------------------------------------------------------------
display_name: chewbbaca
name: chewbbaca__v2.1.4
version:
  schema: ["v2_1_0"]
  code: v2.1.4
  resource: ""
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  target: [sample]
  description: >
    This performs read based cgMLST with the chewbbaca suite https://github.com/B-UMMI/chewBBACA using
    either custom schemas or the ones provided with chewbbaca.
#---------------------------------------------------------------------------------------------------

#-Category info-------------------------------------------------------------------------------------
category: [cgmlst]
#---------------------------------------------------------------------------------------------------

#-Install-------------------------------------------------------------------------------------------
install:
  path: # Set by install program
  dockerfile: docker://ssidk/bifrost_chewbbaca
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
# See this link for available options:
# https://chewbbaca.readthedocs.io/en/latest/user/modules/DownloadSchema.html
# chewBBACA.py DownloadSchema -sp 8 -sc 1 -o resources/Salmonella_enterica_8_1
options:
  chewbbaca_species_mapping: # (name)
    schema:
      Campylobacter jejuni: "campy_v2_pubmlst_20251104_clean_chewBBACA_sizefilter40_st_20p"
      Campylobacter coli: "campy_v2_pubmlst_20251104_clean_chewBBACA_sizefilter40_st_20p"
      Campylobacter lari: "campy_v2_pubmlst_20251104_clean_chewBBACA_sizefilter40_st_20p"
      Campylobacter upsaliensis: "campy_v2_pubmlst_20251104_clean_chewBBACA_sizefilter40_st_20p"
      Campylobacter fetus: "campy_v2_pubmlst_20251104_clean_chewBBACA_sizefilter40_st_20p"
      Campylobacter helveticus: "campy_v2_pubmlst_20251104_clean_chewBBACA_sizefilter40_st_20p"
      Campylobacter sputorum: "campy_v2_pubmlst_20251104_clean_chewBBACA_sizefilter40_st_20p"
      Campylobacter concisus: "campy_v2_pubmlst_20251104_clean_chewBBACA_sizefilter40_st_20p"
      Campylobacter hyointestinalis: "campy_v2_pubmlst_20251104_clean_chewBBACA_sizefilter40_st_20p"
      Escherichia coli: "Escherichia_cgMLSTv1_clean_chewBBACA_sizefilter40_st_25p"
      Shigella sonnei: "Escherichia_cgMLSTv1_clean_chewBBACA_sizefilter40_st_25p"
      Shigella flexneri: "Escherichia_cgMLSTv1_clean_chewBBACA_sizefilter40_st_25p"
      Shigella boydii: "Escherichia_cgMLSTv1_clean_chewBBACA_sizefilter40_st_25p"
      Shigella dysenteriae: "Escherichia_cgMLSTv1_clean_chewBBACA_sizefilter40_st_25p"
      Salmonella enterica: "Salmonella_enterobase_cgMLSTv2_230207_clean_chewBBACA_sizefilter40_st_38p"
      Salmonella bongori: "Salmonella_enterobase_cgMLSTv2_230207_clean_chewBBACA_sizefilter40_st_38p"
      Listeria monocytogenes: "listeria_bigsdb_cgmlst1748_clean_chewBBACA_sizefilter40_st_5p"
      Clostridioides difficile: "cdiff_cgMLST_ridom_clean_chewBBACA_sizefilter40_st_5p"


#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  schemes: "resources/schemes/"

#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    categories:
      contigs:
        summary:
          data:
      assembly_check:
        summary:
          sufficient_assembly: pass
      species_detection:
        summary:
          species:
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files: []
  sample:
    categories:
      cgmlst:
        name:
        summary:  # see sample_component summary
          call_percent:
        component:
          _id: 
          date:  # ObjectId
        report:
          loci: []
          alleles: {}
  sample_component:
    summary:
      sequence_type: 
    results:
      chewbbaca/chewbbaca_results/results_<date><time>/results_alleles.tsv: {}

#---------------------------------------------------------------------------------------------------
