#-Basic info----------------------------------------------------------------------------------------
display_name: chewbbaca
name: &name chewbbaca__v0_0_1__
version:
  schema: ["v2_1_0"]
  code: v0_0_1
  resource: ""
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  target: [sample]
  description: >
    This performs read based cgMLST with the chewbbaca suite https://github.com/B-UMMI/chewBBACA using
    either custom schemas or the ones provided with chewbbaca.
#---------------------------------------------------------------------------------------------------

#-Category info-------------------------------------------------------------------------------------
category: [cgmlst]
#---------------------------------------------------------------------------------------------------

#-Install-------------------------------------------------------------------------------------------
install:
  path: # Set by install program
  dockerfile: docker://ssidk/bifrost_chewbbaca
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
  chewbbaca_species_mapping: 
    Campylobacter jejuni: "Campylobacter"
    Campylobacter coli: "Campylobacter"
    Escherichia coli: "Escherichia coli"
    Shigella sonnei: "Escherichia coli"
    Shigella flex: "Escherichia coli"
    Salmonella enterica: "Salmonella enterica"
    Yersinia enterocolitica: "Yersinia"
    Listeria monocytogenes: "Listeria"

#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  schemes: "/bifrost/components/bifrost_chewbbaca/resources"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    categories:
      paired_reads:
        summary:
          data:
      contigs:
        summary:
          data:
      species_detection:
        summary:
          detected_species:
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files: []
  sample:
    categories:
      cgmlst:
        summary:  # see sample_component summary
        component:
          _id: 
          date:  # ObjectId
    report:
      cgmlst:
        title: "cgmlst"
        info: *name
        columns: 
          - {id: "alleles", name: "alleles"}
        data: []
  sample_component:
    summary:
      sequence_type: 
    results:
      chewbbaca/chewbbaca_results/results_<date><time>/results_alleles.tsv: {}

#---------------------------------------------------------------------------------------------------
