#-Basic info----------------------------------------------------------------------------------------
display_name: chewbbaca
name: chewbbaca__v2.0.0
version:
  schema: ["v2_1_0"]
  code: v2.0.0
  resource: ""
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  target: [sample]
  description: >
    This performs read based cgMLST with the chewbbaca suite https://github.com/B-UMMI/chewBBACA using
    either custom schemas or the ones provided with chewbbaca.
#---------------------------------------------------------------------------------------------------

#-Category info-------------------------------------------------------------------------------------
category: [cgmlst]
#---------------------------------------------------------------------------------------------------

#-Install-------------------------------------------------------------------------------------------
install:
  path: # Set by install program
  dockerfile: docker://ssidk/bifrost_chewbbaca
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
# See this link for available options:
# https://chewbbaca.readthedocs.io/en/latest/user/modules/DownloadSchema.html
# chewBBACA.py DownloadSchema -sp 8 -sc 1 -o resources/Salmonella_enterica_8_1
options:
  chewbbaca_species_mapping: # (name)
    schema:
      Campylobacter jejuni: "Campy_oxford_cgMLST_scheme_chewBBACA_sizefilter40_st_6p"
      Campylobacter coli: "Campy_oxford_cgMLST_scheme_chewBBACA_sizefilter40_st_6p"
      Escherichia coli: "Escherichia_enterobase_cgMLSTv1_chewBBACA_sizefilter40_st_12p"
      Shigella sonnei: "Escherichia_enterobase_cgMLSTv1_chewBBACA_sizefilter40_st_12p"
      Shigella flexneri: "Escherichia_enterobase_cgMLSTv1_chewBBACA_sizefilter40_st_12p"
      Salmonella enterica: "Salmonella_enterobase_cgMLSTv2_230207_chewBBACA_sizefilter40_st_05p"
      Listeria monocytogenes: "Listeria_bigsdb_cgmlst1748_chewBBACA_sizefilter40_st_5p"
      Clostridioides difficile: "Cdiff_enterobase_cgMLSTv1_chewBBACA_sizefilter40_st001p"
    blastdb:
      Campylobacter jejuni: "all_campy_loci_blastdb"
      Campylobacter coli: "all_campy_loci_blastdb"
      Escherichia coli: "all_coli_loci_blastdb"
      Shigella sonnei: "all_coli_loci_blastdb"
      Shigella flexneri: "all_coli_loci_blastdb"
      Salmonella enterica: "all_salm_loci_blastdb"
      Listeria monocytogenes: "all_listeria_loci_blastdb"
      Clostridioides difficile: "all_cdiff_loci_blastdb"
    blatdb_2bit:
      Campylobacter jejuni: "all_campy_loci.2bit"
      Campylobacter coli: "all_campy_loci.2bit"
      Escherichia coli: "all_coli_loci.2bit"
      Shigella sonnei: "all_coli_loci.2bit"
      Shigella flexneri: "all_coli_loci.2bit"
      Salmonella enterica: "all_salm_loci.2bit"
      Listeria monocytogenes: "all_listeria_loci.2bit"
      Clostridioides difficile: "all_cdiff_loci.2bit"
    blatdb_fa:
      Campylobacter jejuni: "all_campy_loci.fa"
      Campylobacter coli: "all_campy_loci.fa"
      Escherichia coli: "all_coli_loci.fa"
      Shigella sonnei: "all_coli_loci.fa"
      Shigella flexneri: "all_coli_loci.fa"
      Salmonella enterica: "all_salm_loci.fa"
      Listeria monocytogenes: "all_listeria_loci.fa"
      Clostridioides difficile: "all_cdiff_loci.fa"

      

#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  schemes: "resources/schemes/"
  blastdb: "resources/blastdb/"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    categories:
      contigs:
        summary:
          data:
      species_detection:
        summary:
          detected_species:
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files: []
  sample:
    categories:
      cgmlst:
        name:
        summary:  # see sample_component summary
          call_percent:
        component:
          _id: 
          date:  # ObjectId
        report:
          loci: []
          alleles: {}
  sample_component:
    summary:
      sequence_type: 
    results:
      chewbbaca/chewbbaca_results/results_<date><time>/results_alleles.tsv: {}

#---------------------------------------------------------------------------------------------------
